<?
$aMenuLinks = Array(
    Array(
        "icon-facebook",
        "https://facebook.com/",
        Array(),
        Array(),
        ""
    ),
    Array(
        "icon-instagram",
        "https://instagram.com/",
        Array(),
        Array(),
        ""
    ),
    Array(
        "icon-drom",
        "https://drom.ru/",
        Array(),
        Array(),
        ""
    )
);
?>